# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  deployment:
    prod:
      branch: master
      commands:
        - aws s3 sync . s3://siim.haas.s3.public.bucket --delete